### ISSUE TITLE
Too many requests: The rate limit has been exceeded

### ISSUE THREAD

**Issue by zorattgi** [plasticuproject/hibpwned#2]
Hello, 

Do you know how many time i must wait until i'll retrieve the access to haveibeenpwned through your api ?

**Comment by plasticuproject** [comment]
@zorattgi 

Mr. Hunt's API does return the amount of time needed to wait for a retry in the response body of the 429 Rate Limit Exceeded Response, but unfortunately I did not code this module to include that in the output.  I will add that in the next update. Thank you for bringing that to my attention. For more information on rate limiting read the Rate Limiting section at the bottom of:
https://haveibeenpwned.com/API/v2

For now, to avoid being rate limited please try to write your application to conform to the following:
```
Requests to the breaches and pastes APIs are limited to one per every 1500 milliseconds
 each from any given IP address
```

**Comment by plasticuproject** [comment]
It should now print the rate limit data when exceeded with the latest commit.
